# Generated by Django 6.0.5 on 2026-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=100, unique=True)),
                ("profile_pic", models.ImageField(upload_to="students/")),
                ("name", models.CharField(max_length=100)),
                (
                    "courses",
                    models.CharField(
                        choices=[
                            ("BCA", "BCA"),
                            ("B.Tech", "B.Tech"),
                            ("MCA", "MCA"),
                            ("BBA", "BBA"),
                            ("MBA", "MBA"),
                        ],
                        max_length=100,
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
