# Generated by Django 6.0.5 on 2026-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_addstudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("roll_no", models.CharField(max_length=20, unique=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                (
                    "courses",
                    models.CharField(
                        choices=[
                            ("BCA", "BCA"),
                            ("B.Tech", "B.Tech"),
                            ("MCA", "MCA"),
                            ("BBA", "BBA"),
                            ("MBA", "MBA"),
                        ],
                        max_length=100,
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
                ("semester", models.PositiveIntegerField()),
                ("date_of_birth", models.DateField()),
                ("admission_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
