# Generated by Django 6.0.5 on 2026-07-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0004_studentsadd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentsadd",
            old_name="roll_no",
            new_name="student_id",
        ),
        migrations.RemoveField(
            model_name="studentsadd",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="studentsadd",
            name="semester",
        ),
        migrations.AddField(
            model_name="studentsadd",
            name="year",
            field=models.CharField(
                choices=[
                    ("1st Year", "1st Year"),
                    ("2nd Year", "2nd Year"),
                    ("3rd Year", "3rd Year"),
                    ("4th Year", "4th Year"),
                ],
                default="1st Year",
                max_length=20,
            ),
        ),
    ]
