# Generated by Django 6.0.5 on 2026-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0005_rename_roll_no_studentsadd_student_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentsAdd",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="roll_no",
            new_name="student_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="semester",
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[
                    ("1st Year", "1st Year"),
                    ("2nd Year", "2nd Year"),
                    ("3rd Year", "3rd Year"),
                    ("4th Year", "4th Year"),
                ],
                default="1st Year",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.CharField(
                choices=[
                    ("BCA", "BCA"),
                    ("B.Tech", "B.Tech"),
                    ("MCA", "MCA"),
                    ("BBA", "BBA"),
                    ("MBA", "MBA"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
