# Generated by Django 6.0.5 on 2026-07-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "MainApp",
            "0006_delete_studentsadd_rename_roll_no_student_student_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
    ]
