# Generated by Django 6.0.5 on 2026-07-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0007_remove_student_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AddStudent",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="admission_date",
            new_name="created_at",
        ),
    ]
