# Generated by Django 6.0.5 on 2026-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0008_delete_addstudent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
