# Generated by Django 6.0.5 on 2026-07-14 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0009_alter_student_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("phone", models.CharField(blank=True, max_length=10)),
                ("dark_mode", models.BooleanField(default=True)),
                ("notifications", models.BooleanField(default=True)),
                (
                    "theme_color",
                    models.CharField(
                        choices=[
                            ("Indigo", "Indigo"),
                            ("Blue", "Blue"),
                            ("Green", "Green"),
                            ("Purple", "Purple"),
                        ],
                        default="Indigo",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
