# Generated by Django 6.0.5 on 2026-07-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0010_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="dark_mode",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="theme_color",
        ),
    ]
