# Generated by Django 6.0.5 on 2026-07-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0011_remove_settings_dark_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
