# Generated by Django 6.0.5 on 2026-07-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0012_student_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
    ]
